apiVersion: v1
kind: Service
metadata:
  name: service-my-node-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 3000 
  selector:
    app: node-app
  type: LoadBalancer